#include "Application.h"

#include "AudioPlayerComponent.h"

/// ProjectInfo globals come from the JuceHeader.h which is generated by the juce_generate_juce_header() Cmake command.
/// This uses the juce_add_gui_app() command's properties to ensure these values are in sync with the build config.

Application::Application() = default;

const String Application::getApplicationName()
{
    return String(ProjectInfo::projectName);
}

const String Application::getApplicationVersion()
{
    return String(ProjectInfo::versionString);
}

void Application::initialise([[maybe_unused]] const String& commandLineParameters) // GUI app, so don't use this arg
{
     m_mainWindow = std::make_unique<MainWindow>("", new AudioPlayerComponent(), *this);
}

void Application::shutdown()
{
    m_mainWindow = nullptr;
}
